### ISSUE TITLE
There is a problem when I use ft16x16 algorithm in nnp_convolution_inference

### ISSUE THREAD

**Issue by tsyj0404** [zeno40/nnpack#2]
Dear developer, @zeno40 

Thank you for your contribution. It works very well in windows platform.

When I choose ft16x16 in in nnp_convolution_inference, the results are not correct. Also, when algorithm_auto is set, it may chose ft16x16 in some convolution layers, but the results are not correct. But wt8x8 and ft8x8 work well.

The following is my experiment. The results of ft16x16 are compared with the results of im2col+cblas_gemm, and the first three elements and the last one are shown. For wt8x8 and ft8x8, the corresponding elements are equal, but for ft16x16, only the result of the first convolution layer is correct.

![image](https://user-images.githubusercontent.com/14989910/27644013-3617d01a-5c55-11e7-9bdf-b999ceb35417.png)

Is there a problem about ft16x16? Or is there something special while using ft16x16?

Thank you.

**Comment by zeno40** [comment]
Hi,

Thanks for reporting.
 I did an update of the nnp_convolution_inference code. Can you repeat your tests with the latest build?

**Comment by tsyj0404** [comment]
Thank you. 

I have made a try with the latest build, but there is an exception from nnp_convolution_inference while using wt8x8, auto, and ft16x16. For ft16x16, the results are equal to these of the above picture.  

I am now using the previous nnpack. Can you provide me a ChangeLog? Then I can build the latest nnpack in my test.

Thank you!

**Comment by zeno40** [comment]
Sorry for the late response!
I did some updates in nnp_convolution_inference.cpp to reflect more the original 
The exception you encountered should be gone. Can you do your test again?
Thanks

**Comment by tsyj0404** [comment]
Sorry for the late response. 

Thanks for your contribution. I still encounter the exception when I use the the latest build in nnp_convolution_inference or nnp_convolution_output. In fact, only the previous nnpack works well in my test, and I can only choose wt8x8 and nnp_convolution_transform_strategy_compute in inference.  Also, ft8x8 works well.

**Comment by tsyj0404** [comment]
In a different cpu, sandybridge, I encounter some problems when I tried to create some objects, such as "2d-fourier-16x16.obj", "winograd-f6k3.obj", but for relu.py, it worked well. 

I got this error while creating winograd-f6k3.obj:
  File "d:\software\peachpy-master\peachpy\writer.py", line 111, in
__exit__
    os.unlink(self.output_file.name)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'winograd-f6k3.obj'

The python is 2.7.12, and cup supports avx, but does not avx2. Is this the problem?  And should I created all the object files according to the the command:
 "python -m peachpy.x86_64 -mabi=ms -mimage-format=ms-coff -mcpu=sandybridge -o winograd-f6k3.obj winograd-f6k3.py"? 

Thank you!

**Comment by zeno40** [comment]
Hi,

Is it possible to mail me the "old" working nnp_convolution_inference.cpp file to dhaene.filip@skynet.be
so I can investigate the culprit I've stupidly lost this file!?
I created a new repo with the original nnpack directory structure wich is needed to properly peachpy all the python scripts to objects.
Concerning support for sandybridge, you should try with the latest repo to peachpy every script for sandybrige cpu. Maybe it is no problem or maybe just a small problem. I don't know the exact scripts who are avx2 only. My experience with python is very limited!

Thanks!

**Comment by tsyj0404** [comment]
hi,
The previous file has been sent.

**Comment by tsyj0404** [comment]
I may make some mistakes in creating objects. I still encounter the previous problems when I try to build the objects in cpu haswell, windows.

"I created a new repo with the original nnpack directory structure", do you mean you build these objects in linux while installing linux_nnpack, and then move them to windows_nnpack?  Can you tell me how to create the repo and use it with the peachpy commands? This problem has been bothering me for a long time...

Thank you!

**Comment by zeno40** [comment]
Thanks for sending me the file!
I see the differences but find it strange the latest version don't work for fft16x16 because I don't find any notable difference with Marat Dukhan repo. I will do some futher testing.

You don't have to build anything in Linux. "I created a new repo with the original nnpack directory structure" just means the repo nnpack-windows has the same directories with the python scripts like in the orignal Linux/mac/android version. This is making objects from the python scripts easier. (the import used in the scripts). 

Tthe steps to build the nnpack-windows repo:
- check you have Visual Studio 2017 and Python installed

Install PeachPy
open a Phyton command prompt:
pip install --upgrade git+https://github.com/Maratyszcza/PeachPy

Download the nnpack-windows repo somewhere and after extracting go in the python prompt to the directory
 ..\nnpack\src\x86_64-fma

Type:
python -m peachpy.x86_64 -mabi=ms -mimage-format=ms-coff -mcpu=haswell -o common.obj common.py

and do the same for every python script in each directory. In the "blas" directory you must first create the avx.obj and avx2.obj object including those in the "fp16" subdirectory.


after all the objects are created you open te visual studio solution file with vs2017

**Comment by tsyj0404** [comment]
Thank you.

Do all the objects are created independently by the similar python command for each python scripts?

I have created other files successfully including the previous winograd-f6k3.obj, and I these source python files are from nnpack-linux, which seem to be used in both windows and linux, but if I use the python files of nnpack-windows, I will encounter the precious error “WindowsError: [Error 32] The process cannot access the file because it is being used by another process: ”.

But now, I still cannot create three objects: sgemm.obj and shdotxf.obj in blas directory, and exp.obj in x86_64-fma directory, because of the above Error 32. It’s a big progress, but what’s the problem for these three files? I use the command to create sgemm.obj:  “python -m peachpy.x86_64 -mabi=ms -mimage-format=ms-coff -mcpu=sandybridge -o sgemm.obj sgemm.py”, and avx.obj  and avx2.obj have been created successfully. Do they compiled independently?

Thanks again. You are a warrior for contributing the excellent projects, both the convnet and nnpack-windows.  An excellent job!
Best Wishes.

**Comment by zeno40** [comment]
Thaks for the very nice compliment!

Have you also build the common.py script in the blas directory because 
sgemm.py needs the common.obj in this directory. shdotxf.py needs the avx.obj and avx2.obj in the blas directory. exp.py in the x86_64fma directory doesn't work for me either. But I don't use the softmax function for now.

**Comment by tsyj0404** [comment]
Thank you. You’re worth it. 

Get a big progress. I am creating objects in haswell, and the only file could not be compiled is o6x6k3x3.obj in winograd directory, where common.py and avx.py have been compiled successfully. So are there some other requirements for compiling this file?

If I want to use nnpack_windows in sandybridge cpu to do test, do I have to install vs2017 and compile nnpack in that cpu? 

Thank you.

**Comment by zeno40** [comment]
Hi,

Strange you couldn't create the o6x6k3x3.obj . I'm running on a haswell proc and don't encounter any
problems. Besides common.py and common.obj there no other dependencies.
If you're trying to get it working for sandybrige cpu you need at least a sandybrige or better cpu to emit sandybrige instructions. In VS2017 you need to enable the AVX extentions instead of the AVX2 extensions otherwise you will not be able to run it on a sandybrige cpu
I've only compiled the code with VS2017 but I think it could be compiled under VS2015 update3 as well.

**Comment by tsyj0404** [comment]
Thank you. 

I have compiled this version under vs2015 successfully. Now I am also analyzing the winograd convolution.  (https://github.com/IntelLabs/SkimCaffe). Some optimizations can be made in winogradLayer.

**Comment by zeno40** [comment]
Glad to hear your build is now successfull!
Are your result for the fft16x16 path now correct?
